// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth():Promise<void>;

export function GetBandwithSpeed():Promise<Array<any>>;

export function GetCpuUsage():Promise<string>;

export function GetRamUsage():Promise<Array<string>>;

export function GetWeather():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Notification(arg1:string,arg2:string):Promise<void>;
