// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth(arg1, arg2, arg3) {
  return window['go']['main']['App']['Auth'](arg1, arg2, arg3);
}

export function GetSystemUsage(arg1) {
  return window['go']['main']['App']['GetSystemUsage'](arg1);
}

export function GetWeather() {
  return window['go']['main']['App']['GetWeather']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Notification(arg1, arg2) {
  return window['go']['main']['App']['Notification'](arg1, arg2);
}

export function UseWindowControl(arg1) {
  return window['go']['main']['App']['UseWindowControl'](arg1);
}
