// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Auth() {
  return window['go']['main']['App']['Auth']();
}

export function GetBandwithSpeed() {
  return window['go']['main']['App']['GetBandwithSpeed']();
}

export function GetCpuUsage() {
  return window['go']['main']['App']['GetCpuUsage']();
}

export function GetRamUsage() {
  return window['go']['main']['App']['GetRamUsage']();
}

export function GetWeather() {
  return window['go']['main']['App']['GetWeather']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Notification(arg1, arg2) {
  return window['go']['main']['App']['Notification'](arg1, arg2);
}
