// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {server} from '../models';

export function Auth(arg1:string,arg2:server.User,arg3:string):Promise<any>;

export function GetSystemUsage(arg1:string):Promise<any>;

export function GetWeather():Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Notification(arg1:string,arg2:string):Promise<void>;

export function UseWindowControl(arg1:string):Promise<any>;
